### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by Michelle-Createment** [MichaelHCioc/M3T1Aufgabe#1]
Die Klasse Raubtier muss lesbarer werden, mache am besten nach jeder Methode einen Absatz und schreibe die letzte Klammer in eine einzelne Zeile, bsp.:

private void methode(){
 //Inhalt
}

private void methode2(){
 //Inhalt
}

**Comment by MichaelHCioc** [comment]
Erledigt. Habe alles schick gemacht
