### ISSUE TITLE
Funktionalität und Sichtbarkeit

### ISSUE THREAD

**Issue by Michelle-Createment** [MichaelHCioc/M3T1Aufgabe#3]
Die berechneDurchhaltevermögen() Methode sollte in der Raubtier-Klasse im Konstruktor aufgerufen werden und private sein :)=
Achte auf die Sichtbarkeit!

**Comment by Michelle-Createment** [comment]
`https://dbs.cs.uni-duesseldorf.de/lehre/docs/java/javabuch/html/k100049.html#sectlevel2id007003`
Schau dir nochmal Methoden an, aber an sich ist der Aufbau so:
[Modifikator für Sichtbarkeit] [Typ, also: void, int, String, Object,....] methodenName ([Parameter, also int i, Sting a, etc.]) {
  //Anweisungen
}

Aufrufen kannst du die Methode dann mit:

methodenName([Parameter]);

Wenn die Methode einen return Wert hat, kannst du auch diesen Wert direkt einer Variable zuweisen.

**Comment by MichaelHCioc** [comment]
Denke das Problem ist gelöst
